{% set name = "napari-tomotwin" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-tomotwin-{{ version }}.tar.gz
  sha256: e25cb06896325a7d558c131685dbaa41d10091ff03d9cc7bb7ba382330a785f8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools-scm
  run:
    - magicgui
    - matplotlib-base
    - napari
    - napari-clusters-plotter >=0.7.2
    - numpy
    - pandas
    - python >=3.10
    - scipy

test:
  imports:
    - napari_tomotwin
  commands:
    - pip list
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/MPI-Dortmund/napari-tomotwin
  summary: Several tools for the work with TomoTwin
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - thorstenwagner
